Course annotation tool
davidgengenbach/tucan-catalog pull request #4
Opened 2020-10-06 14:51 UTC by pkwagner

In addition to the already implemented course hiding functionality, this PR allows choosing an individual annotation color for each module.

<img width="1680" alt="Screenshot 2020-10-06 at 16 51 04" src="https://user-images.githubusercontent.com/22484496/95218022-2212bc80-07f4-11eb-9664-c4a902d398e1.png">

2020-10-06 17:25 UTC, davidgengenbach requested changes

2020-10-06 17:25 UTC, davidgengenbach commented on index.html
> +            <button ng-click="setAnnotation(selectedNode, 1)" class="annotation annotation-1" ng-class="{'annotation-active': selectedNode.annotation === 1}">&nbsp;</button>
The following lines are a little repetitious - can you maybe put the annotations (in this case `[1, 2, 3, 4, 5]`) in the `$scope` and repeat via `ng-repeat` over them (= generating the buttons dynamically).

2020-10-06 17:25 UTC, davidgengenbach commented on index.html
> +                <div data-angular-treeview="true" data-tree-id="tree" data-tree-model="data" data-node-id="label" data-node-label="label" data-node-children="children" data-label-template="<span clas
I know this is more of my fault but can you please break this rather long line into more lines?

2020-10-06 17:26 UTC, davidgengenbach commented
Very nice addition! I will not maintain this project any longer as I finished my studies at TU Darmstadt. 

Would you be interested in becoming the maintainer of this repository (and maybe the whole TuCan "suite", e.g., `tucan-tools`, as well)?

2020-10-08 15:50 UTC, pkwagner commented
Thanks for the feedback, I'll push it later today!

2020-10-18 21:25 UTC, davidgengenbach approved these changes

2020-10-18 21:25 UTC, merged